### ISSUE TITLE
Spring Session MongoDB

### ISSUE THREAD

**Issue by dussab** [tmurakam/spring-session-ext-mongo#6]
Hi Takuya,
I lead the Spring engineering team at Pivotal and noticed that your project has a conflicting project name with one of our projects of the same name (https://spring.io/blog/2017/06/16/spring-session-mongodb-2-0-0-m1-released). I wonder if you would be open to combining efforts on our project. Alternatively, I would request that you rename your project to avoid any branding confusion within the Spring community. 

Thanks,
Brian

**Comment by tmurakam** [comment]
I'm using this name since August 2015, and already we use it in our products, so it is bit hard to change the artifact name....

But I understood your situation, so I consider to try to change the project name.

**Comment by tmurakam** [comment]
I had changed the project name, and artifact name.
